### ISSUE TITLE
It is not working for Strapi v3.0.1

### ISSUE THREAD

**Issue by geberele** [alessandrocaprarelli/strapi-provider-email-mailtrap#1]

**Comment by geberele** [comment]
This is the fix for the version 3.0.1 of Strapi:
[strapi-provider-email-mailtrap.zip](https://github.com/alessandrocaprarelli/strapi-provider-email-mailtrap/files/4743999/strapi-provider-email-mailtrap.zip)
If you want to give me permission to the repo I will create a pull request with the changes in the files attached.
Thanks

**Comment by alcaprar** [comment]
Hi @geberele , thanks for posting.
You can fork the project and then send a PR.

**Comment by ardiansyaherwin** [comment]
Hi @alessandrocaprarelli is it because now Strapi only use API KEY? btw, do you know how to make mailtrap works to send email from localhost?

**Comment by geberele** [comment]
Hi @alessandrocaprarelli, I have created a PR for this issue https://github.com/alessandrocaprarelli/strapi-provider-email-mailtrap/pull/2

**Comment by alcaprar** [comment]
@geberele I merged the PR and released a new version of the package: `v1.0.2`: https://www.npmjs.com/package/strapi-provider-email-mailtrap/v/1.0.2

**Comment by geberele** [comment]
You are right about the version, sorry, I have created a new PR for the new version https://github.com/alessandrocaprarelli/strapi-provider-email-mailtrap/pull/3
