### ISSUE TITLE
Setup strapi 3.1.4

### ISSUE THREAD

**Issue by clickanidea** [alessandrocaprarelli/strapi-provider-email-mailtrap#4]
Ciao Alessandro,
I am struggling making the plugin work:

1. added with yarn
2. no config option in Plugin menu, just 'Emails - Send Emails'
3. tried to play around with plugin.js but I could not find any help anywhere..

Could you point me to the right direction, please ?
Grazie !

**Comment by alcaprar** [comment]
Hi @clickanidea, sorry for the late reply.
I just published a new version of the provider that works with strapi 3.1.5. Can you try it?
